# This is for the dronie 1.0 agent
# https://docs.drone.io/user-guide/pipeline/steps/ https://docs.drone.io/user-guide/pipeline/migrating/
# See https://git.osgeo.org/gitea/geos/geos-docker
test-image: &test-image docker.osgeo.org/geos/build-test:alpine

kind: pipeline
name: default

clone:
    image: plugins/git
    depth: 50
    recursive: false

steps:
  - name: build
    image: *test-image
    pull: always
    commands:
      - ./autogen.sh
      - CXXFLAGS="-O0" ./configure
      - make V=0
  - name: check
    image: *test-image
    commands:
      - CXXFLAGS="-O0" make check V=0
  # - name: docs
  #   image: *test-image
  #   commands:
  #     - make doxygen-checked
  # - name: valgrindcheck
  #   image: *test-image
  #   commands:
  #     - CXXFLAGS="-O0" make valgrindcheck V=0
